#!/usr/bin/env python3
"""#23 Amendment 3 isolation arms (pre-registered decision rules in CLAIMS).
  ISO_BR  A3a16-BASE-READER: same retrieved top-16 lines as the full run's A3a16,
          final answer generated by BASE (adapter off). Tests frozen-implementability.
  ISO_AD  A3a16-ADAPTER-DRAFT: draft generated WITH the memory adapter, embed top-16
          over that draft, answer with adapter reader (same reader as A3a16).
          Tests the user token-leak hypothesis at the retrieval layer.
Primary readouts: gold_in deltas + draft_adapter saved for token-overlap analysis;
judged IA reported but not part of the confirm rule. Out results/inmind/answers_iso.json"""
import json, os, sys

import torch
from transformers import AutoModel, AutoModelForCausalLM, AutoTokenizer
from peft import LoraConfig, get_peft_model

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "e0"))
import e0_lib as L

DEV = "cuda:0"
L.check_env()
MODEL = "Qwen/Qwen3.5-9B"
HERE = os.path.dirname(__file__)

tasks = [json.loads(l) for l in open(os.path.join(HERE, "inmind_bench", "benchmark",
                                                  "dataset", "inmind.jsonl"))]
N = len(tasks)
LOG = [f"[session {i:03d}] {t['user_message']}" for i, t in enumerate(tasks)]
full = json.load(open(os.path.join(HERE, "results", "inmind", "answers_full.json")))
frow = {r["task_id"]: r for r in full["rows"]}

tok = AutoTokenizer.from_pretrained(MODEL)
base = AutoModelForCausalLM.from_pretrained(MODEL, torch_dtype=torch.bfloat16).to(DEV)
cfg = LoraConfig(r=64, lora_alpha=128, target_modules="all-linear",
                 lora_dropout=0.0, bias="none", task_type="CAUSAL_LM")
model = get_peft_model(base, cfg, adapter_name="mem")
model.load_state_dict(torch.load(os.path.join(HERE, "results", "inmind",
                                 "adapter_full.pt"), map_location=DEV), strict=False)
model.eval()
etok = AutoTokenizer.from_pretrained("BAAI/bge-small-en-v1.5")
emb = AutoModel.from_pretrained("BAAI/bge-small-en-v1.5").to(DEV).eval()

@torch.no_grad()
def embed(texts):
    b = etok(texts, padding=True, truncation=True, return_tensors="pt").to(DEV)
    return torch.nn.functional.normalize(emb(**b).last_hidden_state[:, 0], dim=-1)

LOGV = embed(LOG)

def etop(text, k):
    qv = embed([text])
    return [LOG[i] for i in torch.argsort((LOGV @ qv.T).squeeze(1), descending=True)[:k].tolist()]

def chat(content, use_adapter, max_new=300):
    msgs = [{"role": "user", "content": content}]
    p = tok.apply_chat_template(msgs, tokenize=False, add_generation_prompt=True,
                                enable_thinking=False)
    inp = tok(p, return_tensors="pt").to(DEV)
    with torch.no_grad():
        if use_adapter:
            g = model.generate(**inp, max_new_tokens=max_new, do_sample=False,
                               pad_token_id=tok.pad_token_id or tok.eos_token_id)
        else:
            with model.disable_adapter():
                g = model.generate(**inp, max_new_tokens=max_new, do_sample=False,
                                   pad_token_id=tok.pad_token_id or tok.eos_token_id)
    return tok.decode(g[0][inp["input_ids"].shape[1]:], skip_special_tokens=True).strip()

ANSWER = ("{q}\n\nAnswer the user helpfully and concisely.")
RAG = ("Here are entries from the user's memory log:\n{log}\n\n{q}\n\n"
       "Answer the user helpfully and concisely, taking any relevant personal facts "
       "from the log into account.")

rows = []
for i, t in enumerate(tasks):
    q = t["query"]
    fr = frow[t["task_id"]]
    r_br = fr["arms"]["A3a16"]["ret"]
    a_br = chat(RAG.format(log="\n".join(r_br), q=q), use_adapter=False)
    draft_a = chat(ANSWER.format(q=q), use_adapter=True)
    r_ad = etop(draft_a, 16)
    a_ad = chat(RAG.format(log="\n".join(r_ad), q=q), use_adapter=True)
    gold_ln = LOG[i]
    row = {"task_id": t["task_id"], "domain": t["domain"],
           "draft_adapter": draft_a, "draft_base": fr["draft"],
           "arms": {"ISO_BR": {"ans": a_br, "ret": r_br},
                    "ISO_AD": {"ans": a_ad, "ret": r_ad}},
           "gold_in": {"ISO_BR": int(any(gold_ln == r for r in r_br)),
                       "ISO_AD": int(any(gold_ln == r for r in r_ad))}}
    rows.append(row)
    print(f"[inmind-iso] {i:3d} gold_in BR={row['gold_in']['ISO_BR']} "
          f"AD={row['gold_in']['ISO_AD']}", flush=True)

summary = {"n": N, "target_recall": {k: sum(r["gold_in"][k] for r in rows) / N
                                     for k in rows[0]["gold_in"]}}
odir = os.path.join(HERE, "results", "inmind")
json.dump({"summary": summary, "rows": rows},
          open(os.path.join(odir, "answers_iso.json"), "w"), indent=1)
print(json.dumps(summary, indent=1))
